<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260603211821 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE album (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(160) NOT NULL, publisher VARCHAR(80) NOT NULL, year INT DEFAULT NULL, description TEXT DEFAULT NULL, stickers_per_pack INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_39986E43989D9B62 ON album (slug)');
        $this->addSql('CREATE TABLE sticker (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(20) NOT NULL, name VARCHAR(150) NOT NULL, team VARCHAR(100) DEFAULT NULL, rarity VARCHAR(255) NOT NULL, position INT NOT NULL, album_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8FEDBCFD1137ABCF ON sticker (album_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_sticker_album_number ON sticker (album_id, number)');
        $this->addSql('CREATE TABLE trade_proposal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, from_user_id INT NOT NULL, to_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EBC843032130303A ON trade_proposal (from_user_id)');
        $this->addSql('CREATE INDEX IDX_EBC8430329F6EE60 ON trade_proposal (to_user_id)');
        $this->addSql('CREATE TABLE trade_proposal_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, direction VARCHAR(255) NOT NULL, quantity INT NOT NULL, proposal_id INT NOT NULL, sticker_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AE0935D9F4792058 ON trade_proposal_item (proposal_id)');
        $this->addSql('CREATE INDEX IDX_AE0935D94D965A4D ON trade_proposal_item (sticker_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, display_name VARCHAR(60) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, country VARCHAR(2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE user_album (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, album_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB5A951BA76ED395 ON user_album (user_id)');
        $this->addSql('CREATE INDEX IDX_DB5A951B1137ABCF ON user_album (album_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_album ON user_album (user_id, album_id)');
        $this->addSql('CREATE TABLE user_sticker (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, user_id INT NOT NULL, sticker_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D7E0A2F7A76ED395 ON user_sticker (user_id)');
        $this->addSql('CREATE INDEX IDX_D7E0A2F74D965A4D ON user_sticker (sticker_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_sticker ON user_sticker (user_id, sticker_id)');
        $this->addSql('ALTER TABLE sticker ADD CONSTRAINT FK_8FEDBCFD1137ABCF FOREIGN KEY (album_id) REFERENCES album (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trade_proposal ADD CONSTRAINT FK_EBC843032130303A FOREIGN KEY (from_user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trade_proposal ADD CONSTRAINT FK_EBC8430329F6EE60 FOREIGN KEY (to_user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trade_proposal_item ADD CONSTRAINT FK_AE0935D9F4792058 FOREIGN KEY (proposal_id) REFERENCES trade_proposal (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trade_proposal_item ADD CONSTRAINT FK_AE0935D94D965A4D FOREIGN KEY (sticker_id) REFERENCES sticker (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_album ADD CONSTRAINT FK_DB5A951BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_album ADD CONSTRAINT FK_DB5A951B1137ABCF FOREIGN KEY (album_id) REFERENCES album (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_sticker ADD CONSTRAINT FK_D7E0A2F7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_sticker ADD CONSTRAINT FK_D7E0A2F74D965A4D FOREIGN KEY (sticker_id) REFERENCES sticker (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sticker DROP CONSTRAINT FK_8FEDBCFD1137ABCF');
        $this->addSql('ALTER TABLE trade_proposal DROP CONSTRAINT FK_EBC843032130303A');
        $this->addSql('ALTER TABLE trade_proposal DROP CONSTRAINT FK_EBC8430329F6EE60');
        $this->addSql('ALTER TABLE trade_proposal_item DROP CONSTRAINT FK_AE0935D9F4792058');
        $this->addSql('ALTER TABLE trade_proposal_item DROP CONSTRAINT FK_AE0935D94D965A4D');
        $this->addSql('ALTER TABLE user_album DROP CONSTRAINT FK_DB5A951BA76ED395');
        $this->addSql('ALTER TABLE user_album DROP CONSTRAINT FK_DB5A951B1137ABCF');
        $this->addSql('ALTER TABLE user_sticker DROP CONSTRAINT FK_D7E0A2F7A76ED395');
        $this->addSql('ALTER TABLE user_sticker DROP CONSTRAINT FK_D7E0A2F74D965A4D');
        $this->addSql('DROP TABLE album');
        $this->addSql('DROP TABLE sticker');
        $this->addSql('DROP TABLE trade_proposal');
        $this->addSql('DROP TABLE trade_proposal_item');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_album');
        $this->addSql('DROP TABLE user_sticker');
    }
}
